version: "3.7"

services:

  grafana:
    image: "grafana/grafana-arm32v7-linux:dev-musl"
    ports: 
      - "3000:3000"
    env_file: .env/env.grafana
    volumes:
      - "grafana-storage:/var/lib/grafana"

  influxdb:
    image: arm32v7/influxdb
    ports:
      - "8086:8086"
    env_file: .env/env.influxdb

volumes:
  grafana-storage:
