version: "3.7"

services: 

  influxdb:
    image: arm32v7/influxdb
    ports: 
      - "8086:8086"
    env_file: .env/env.influxdb
    volumes:
      - "influxdb-storage:/var/lib/influxdb"

  telegraf:
    image: arm32v7/telegraf
    env_file: .env/env.telegraf
    volumes:
      # read telegraf config from host
      - type: bind
        source: ./telegraf.conf
        target: /etc/telegraf/telegraf.conf
        read_only: true
      # monitor RPi's /proc, not container's
      - type: bind
        source: /proc
        target: /host/proc
        read_only: true
    depends_on:
      - influxdb

  grafana:
    image: "grafana/grafana-arm32v7-linux:dev-musl"
    ports: 
      - "3000:3000"
    env_file: .env/env.grafana
    volumes:
      - "grafana-storage:/var/lib/grafana"
    depends_on:
      - influxdb
      - telegraf

volumes:
  grafana-storage:
  influxdb-storage:
